apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storage
  annotations:
    argocd.argoproj.io/sync-wave: "110"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: openshift-storage
    server: https://kubernetes.default.svc
  project: infra
  source:
    path: 1-infra/storage
    repoURL: github.com/yliu138/multi-tenancy-gitops.git
    targetRevision: demo-mq-v2-yliu138
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
