apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-instance
  annotations:
    argocd.argoproj.io/sync-wave: "250"
  labels:
    gitops.tier.group: cntk
spec:
  destination:
    namespace: openshift-operators
    server: 'https://kubernetes.default.svc'
  project: services
  source:
    path: 2-services/instances/cert-manager
    repoURL: https://github.com/yliu138/multi-tenancy-gitops.git
    targetRevision: demo-mq-v2-yliu138
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
